#ifndef _CB_FNS_H_
#define _CB_FNS_H_

/*
** This file is auto-generated by the MX800 Form Manager tool.
** Do not modify the contents of this file by hand!
*/

void SigCap_BTN_ACCEPT_OnClick(char* strFormName, int iControlID, void* pData);
void SigCap_BTN_CANCEL_OnClick(char* strFormName, int iControlID, void* pData);
void TranInfo_BTN_1_OnClick(char* strFormName, int iControlID, void* pData);
void TRANINFO_BTN_2_OnClick(char* strFormName, int iControlID, void* pData);
void SigCap_BTN_ACCEPT_OnClick(char* strFormName, int iControlID, void* pData);
void SigCap_BTN_CANCEL_OnClick(char* strFormName, int iControlID, void* pData);
void TranInfo_BTN_1_OnClick(char* strFormName, int iControlID, void* pData);
void TRANINFO_BTN_2_OnClick(char* strFormName, int iControlID, void* pData);
void SigCap_BTN_ACCEPT_OnClick(char* strFormName, int iControlID, void* pData);
void SigCap_BTN_CANCEL_OnClick(char* strFormName, int iControlID, void* pData);
void TranInfo_BTN_1_OnClick(char* strFormName, int iControlID, void* pData);
void TRANINFO_BTN_2_OnClick(char* strFormName, int iControlID, void* pData);
void SigCap_BTN_ACCEPT_OnClick(char* strFormName, int iControlID, void* pData);
void SigCap_BTN_CANCEL_OnClick(char* strFormName, int iControlID, void* pData);
void TranInfo_BTN_1_OnClick(char* strFormName, int iControlID, void* pData);
void TRANINFO_BTN_2_OnClick(char* strFormName, int iControlID, void* pData);
void SigCap_BTN_ACCEPT_OnClick(char* strFormName, int iControlID, void* pData);
void SigCap_BTN_CANCEL_OnClick(char* strFormName, int iControlID, void* pData);
void TranInfo_BTN_1_OnClick(char* strFormName, int iControlID, void* pData);
void TRANINFO_BTN_2_OnClick(char* strFormName, int iControlID, void* pData);

#endif /* _CB_FNS_H_ */
