/*
** This file is auto-generated by the MX800 Form Manager tool.
** Do not modify the contents of this file by hand!
*/

#include "cb_fns.h"

typedef void (*Event_Callback_Function)(char *pszFormName, int iControlID, void *pData);

Event_Callback_Function cb_Functions[] = 
{
    0,
    SigCap_BTN_ACCEPT_OnClick,
    SigCap_BTN_CANCEL_OnClick,
    TranInfo_BTN_1_OnClick,
    TRANINFO_BTN_2_OnClick,
    SigCap_BTN_ACCEPT_OnClick,
    SigCap_BTN_CANCEL_OnClick,
    TranInfo_BTN_1_OnClick,
    TRANINFO_BTN_2_OnClick,
    SigCap_BTN_ACCEPT_OnClick,
    SigCap_BTN_CANCEL_OnClick,
    TranInfo_BTN_1_OnClick,
    TRANINFO_BTN_2_OnClick,
    SigCap_BTN_ACCEPT_OnClick,
    SigCap_BTN_CANCEL_OnClick,
    TranInfo_BTN_1_OnClick,
    TRANINFO_BTN_2_OnClick,
    SigCap_BTN_ACCEPT_OnClick,
    SigCap_BTN_CANCEL_OnClick,
    TranInfo_BTN_1_OnClick,
    TRANINFO_BTN_2_OnClick,
};
