#ifndef _CTRLIDS_H_
#define _CTRLIDS_H_

/*
** This file is auto-generated by the MX800 Form Manager tool.
** Do not modify the contents of this file by hand!
*/

/* Control IDs for Form FONTDEF */
#define FONTDEF_LBL_1                    1
#define FONTDEF_LBL_2                    2
#define FONTDEF_LBL_3                    3
#define FONTDEF_LBL_4                    4
#define FONTDEF_LBL_5                    5
#define FONTDEF_LBL_6                    6
#define FONTDEF_LBL_7                    7
#define FONTDEF_LBL_8                    8
#define FONTDEF_LBL_9                    9

/* Control IDs for Form IDLE */
#define IDLE_LBL_1                       1
#define IDLE_LBL_2                       2
#define IDLE_ANI_1                       3

/* Control IDs for Form SIGCAP */
#define SIGCAP_LBL_MESSAGE               1
#define SIGCAP_BTN_ACCEPT                2
#define SIGCAP_BTN_CANCEL                3
#define SIGCAP_LBL_TERMS1                4
#define SIGCAP_LBL_TERMS2                5
#define SIGCAP_BOX_1                     6
#define SIGCAP_LIN_1                     7
#define SIGCAP_LBL_4                     8
#define SIGCAP_LBL_5                     9
#define SIGCAP_LBL_6                     10

/* Control IDs for Form TRANINFO */
#define TRANINFO_LBL_MESSAGE             1
#define TRANINFO_LST_ITEMS               2
#define TRANINFO_LBL_SSUBTOTAL           3
#define TRANINFO_LBL_STAX                4
#define TRANINFO_LBL_STOTAL              5
#define TRANINFO_LBL_SUBTOTAL            6
#define TRANINFO_LBL_TAX                 7
#define TRANINFO_LBL_TOTAL               8
#define TRANINFO_ANI_SWIPE               9
#define TRANINFO_LIN_1                   10
#define TRANINFO_LBL_QUESTION            11
#define TRANINFO_BTN_1                   12
#define TRANINFO_BTN_2                   13

/* Control IDs for Form 830_IDLE */
#define IDLE_LBL_1                       1
#define IDLE_LBL_2                       2
#define IDLE_ANI_1                       3

/* Control IDs for Form 830_SIGCAP */
#define SIGCAP_LBL_MESSAGE               1
#define SIGCAP_BTN_ACCEPT                2
#define SIGCAP_BTN_CANCEL                3
#define SIGCAP_LBL_TERMS1                4
#define SIGCAP_LBL_TERMS2                5
#define SIGCAP_BOX_1                     6
#define SIGCAP_LIN_1                     7
#define SIGCAP_LBL_4                     8
#define SIGCAP_LBL_5                     9
#define SIGCAP_LBL_6                     10

/* Control IDs for Form 830_TRANINFO */
#define TRANINFO_LBL_MESSAGE             1
#define TRANINFO_LST_ITEMS               2
#define TRANINFO_LBL_SSUBTOTAL           3
#define TRANINFO_LBL_STAX                4
#define TRANINFO_LBL_STOTAL              5
#define TRANINFO_LBL_SUBTOTAL            6
#define TRANINFO_LBL_TAX                 7
#define TRANINFO_LBL_TOTAL               8
#define TRANINFO_ANI_SWIPE               9
#define TRANINFO_LIN_1                   10
#define TRANINFO_LBL_QUESTION            11
#define TRANINFO_BTN_1                   12
#define TRANINFO_BTN_2                   13

/* Control IDs for Form 850_IDLE */
#define IDLE_LBL_1                       1
#define IDLE_LBL_2                       2
#define IDLE_ANI_1                       3

/* Control IDs for Form 850_SIGCAP */
#define SIGCAP_LBL_MESSAGE               1
#define SIGCAP_BTN_ACCEPT                2
#define SIGCAP_BTN_CANCEL                3
#define SIGCAP_LBL_TERMS1                4
#define SIGCAP_LBL_TERMS2                5
#define SIGCAP_BOX_1                     6
#define SIGCAP_LIN_1                     7
#define SIGCAP_LBL_4                     8
#define SIGCAP_LBL_5                     9
#define SIGCAP_LBL_6                     10

/* Control IDs for Form 850_TRANINFO */
#define TRANINFO_LBL_MESSAGE             1
#define TRANINFO_LST_ITEMS               2
#define TRANINFO_LBL_SSUBTOTAL           3
#define TRANINFO_LBL_STAX                4
#define TRANINFO_LBL_STOTAL              5
#define TRANINFO_LBL_SUBTOTAL            6
#define TRANINFO_LBL_TAX                 7
#define TRANINFO_LBL_TOTAL               8
#define TRANINFO_ANI_SWIPE               9
#define TRANINFO_LIN_1                   10
#define TRANINFO_LBL_QUESTION            11
#define TRANINFO_BTN_1                   12
#define TRANINFO_BTN_2                   13

/* Control IDs for Form 860_IDLE */
#define IDLE_LBL_1                       1
#define IDLE_LBL_2                       2
#define IDLE_ANI_1                       3

/* Control IDs for Form 860_SIGCAP */
#define SIGCAP_LBL_MESSAGE               1
#define SIGCAP_BTN_ACCEPT                2
#define SIGCAP_BTN_CANCEL                3
#define SIGCAP_LBL_TERMS1                4
#define SIGCAP_LBL_TERMS2                5
#define SIGCAP_BOX_1                     6
#define SIGCAP_LIN_1                     7
#define SIGCAP_LBL_4                     8
#define SIGCAP_LBL_5                     9
#define SIGCAP_LBL_6                     10

/* Control IDs for Form 860_TRANINFO */
#define TRANINFO_LBL_MESSAGE             1
#define TRANINFO_LST_ITEMS               2
#define TRANINFO_LBL_SSUBTOTAL           3
#define TRANINFO_LBL_STAX                4
#define TRANINFO_LBL_STOTAL              5
#define TRANINFO_LBL_SUBTOTAL            6
#define TRANINFO_LBL_TAX                 7
#define TRANINFO_LBL_TOTAL               8
#define TRANINFO_ANI_SWIPE               9
#define TRANINFO_LIN_1                   10
#define TRANINFO_LBL_QUESTION            11
#define TRANINFO_BTN_1                   12
#define TRANINFO_BTN_2                   13

/* Control IDs for Form 880_IDLE */
#define IDLE_LBL_1                       1
#define IDLE_LBL_2                       2
#define IDLE_ANI_1                       3

/* Control IDs for Form 880_SIGCAP */
#define SIGCAP_LBL_MESSAGE               1
#define SIGCAP_BTN_ACCEPT                2
#define SIGCAP_BTN_CANCEL                3
#define SIGCAP_LBL_TERMS1                4
#define SIGCAP_LBL_TERMS2                5
#define SIGCAP_BOX_1                     6
#define SIGCAP_LIN_1                     7
#define SIGCAP_LBL_4                     8
#define SIGCAP_LBL_5                     9
#define SIGCAP_LBL_6                     10

/* Control IDs for Form 880_TRANINFO */
#define TRANINFO_LBL_MESSAGE             1
#define TRANINFO_LST_ITEMS               2
#define TRANINFO_LBL_SSUBTOTAL           3
#define TRANINFO_LBL_STAX                4
#define TRANINFO_LBL_STOTAL              5
#define TRANINFO_LBL_SUBTOTAL            6
#define TRANINFO_LBL_TAX                 7
#define TRANINFO_LBL_TOTAL               8
#define TRANINFO_ANI_SWIPE               9
#define TRANINFO_LIN_1                   10
#define TRANINFO_LBL_QUESTION            11
#define TRANINFO_BTN_1                   12
#define TRANINFO_BTN_2                   13

#endif /* _CTRLIDS_H_ */
