/**
 * CONFIDENTIAL AND PROPRIETARY SOURCE CODE. 
 * 
 * Use and distribution of this code is subject to applicable 
 * licenses and the permission of the code owner.  This notice 
 * does not indicate the actual or intended publication of 
 * this source code.
 * 
 * Portions developed for Camping World by BTM Global Consulting
 * LLC and are the property of Camping World.
 * 
 * ===== BTM Modification ===========================================
 * Req/Bug ID#      ddMMyy    Description
 * BZ23405          160118    [QAS] There are problem when integrate Xstore with QAS service of Camping World
 *===================================================================
 */

package caw.qas.proweb;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "QAFault", targetNamespace = "http://www.qas.com/web-2013-12")
public class CawFault extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CawQAFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CawFault(String message, CawQAFault faultInfo) {

        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CawFault(String message, CawQAFault faultInfo, Throwable cause) {

        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: caw.qas.proweb.QAFault
     */
    public CawQAFault getFaultInfo() {

        return faultInfo;
    }

}
