/**
 * CONFIDENTIAL AND PROPRIETARY SOURCE CODE. 
 * 
 * Use and distribution of this code is subject to applicable 
 * licenses and the permission of the code owner.  This notice 
 * does not indicate the actual or intended publication of 
 * this source code.
 * 
 * Portions developed for Camping World by BTM Global Consulting
 * LLC and are the property of Camping World.
 * 
 * ===== BTM Modification ===========================================
 * Req/Bug ID#      ddMMyy    Description
 * BZ23405          160118    [QAS] There are problem when integrate Xstore with QAS service of Camping World
 *===================================================================
 */

package caw.qas.proweb;

import javax.jws.*;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QAPortType", targetNamespace = "http://www.qas.com/web-2013-12")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ CawObjectFactory.class })
public interface CawQAPortType {

    /**
     * 
     * @param body
     * @return
     *     returns caw.qas.proweb.QASearchResult
     * @throws Fault
     */
    @WebMethod(operationName = "DoSearch", action = "http://www.qas.com/web-2013-12/DoSearch")
    @WebResult(name = "QASearchResult", targetNamespace = "http://www.qas.com/web-2013-12", partName = "body")
    public CawQASearchResult doSearch(
            @WebParam(name = "QASearch", targetNamespace = "http://www.qas.com/web-2013-12", partName = "body") CawQASearch body)
            throws CawFault;

    /**
     * 
     * @param body
     * @return
     *     returns caw.qas.proweb.Picklist
     * @throws Fault
     */
    @WebMethod(operationName = "DoRefine", action = "http://www.qas.com/web-2013-12/DoRefine")
    @WebResult(name = "Picklist", targetNamespace = "http://www.qas.com/web-2013-12", partName = "body")
    public CawPicklist doRefine(
            @WebParam(name = "QARefine", targetNamespace = "http://www.qas.com/web-2013-12", partName = "body") CawQARefine body)
            throws CawFault;

}
