--BZ28013 changed password for 100 and 104; removed password of the rest of users
-- START IMPORT DATA OF 10 TEST USERS
--hrs_employee
DELETE FROM HRS_EMPLOYEE WHERE ORGANIZATION_ID = $(OrgID) AND EMPLOYEE_ID IN ('100', '104');
INSERT INTO HRS_EMPLOYEE (ORGANIZATION_ID, EMPLOYEE_ID, LOGIN_ID, PARTY_ID, JOB_TITLE, MARITAL_STATUS, CLOCK_IN_NOT_REQ_FLAG, EMPLOYEE_ROLE_CODE, GROUP_MEMBERSHIP, PRIMARY_GROUP, EMPLOYEE_TYPCODE, TRAINING_STATUS_ENUM, LOCKED_OUT_FLAG, OVERTIME_ELIGIBLE_FLAG, EMPLOYEE_GROUP_ID, EMPLOYEE_STATCODE, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID) VALUES ($(OrgID), '100', '100', 100, 'STORE MANAGER', 'S', 1, 'DEFAULT', 'CQA=', 'STORE_MANAGER', 'DEFAULT', 'EXEMPT', 0, 1, 'DEFAULT', 'A', SYSDATE, 'BASEDATA', SYSDATE, 'BASEDATA');
INSERT INTO HRS_EMPLOYEE (ORGANIZATION_ID, EMPLOYEE_ID, LOGIN_ID, PARTY_ID, JOB_TITLE, MARITAL_STATUS, CLOCK_IN_NOT_REQ_FLAG, EMPLOYEE_ROLE_CODE, GROUP_MEMBERSHIP, PRIMARY_GROUP, EMPLOYEE_TYPCODE, TRAINING_STATUS_ENUM, LOCKED_OUT_FLAG, OVERTIME_ELIGIBLE_FLAG, EMPLOYEE_GROUP_ID, EMPLOYEE_STATCODE, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID) VALUES ($(OrgID), '104', '104', 104, 'ADMINISTRATOR', 'S', 1, 'DEFAULT', 'AQI=', 'ADMINISTRATOR', 'DEFAULT', 'EXEMPT', 0, 1, 'DEFAULT', 'A', SYSDATE, 'BASEDATA', SYSDATE, 'BASEDATA');

-- hrs_employee_password
DELETE FROM HRS_EMPLOYEE_PASSWORD WHERE ORGANIZATION_ID = $(OrgID) AND EMPLOYEE_ID IN ('100', '104');
INSERT INTO HRS_EMPLOYEE_PASSWORD (ORGANIZATION_ID, EMPLOYEE_ID, PASSWORD, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID) VALUES ($(OrgID), '100', '{SHA512}40953b03b835d1f2dbcaf4a12902036e784333fb793d04a88aaed62974a2aebca58442267b2858c5c8795a441c3526d38989eb0768ed2bec8ceeeab03e4fce0d$86c54beb5ef9b504$100000', SYSDATE, 'BASEDATA', SYSDATE, 'BASEDATA');
INSERT INTO HRS_EMPLOYEE_PASSWORD (ORGANIZATION_ID, EMPLOYEE_ID, PASSWORD, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID) VALUES ($(OrgID), '104', '{SHA512}40a604fc83342d216874e48989e14a76c236c5d283cf22e4c0633c7f8e46490aeadc246906fd97e405d309c16bbbec23aa6dd49e84a15db3b2d730ae9dbb2b04$65163fe4befee6ae$100000', SYSDATE, 'BASEDATA', SYSDATE, 'BASEDATA');

--hrs_employee_store
DELETE FROM HRS_EMPLOYEE_STORE WHERE ORGANIZATION_ID = $(OrgID) AND RTL_LOC_ID = $(StoreID) AND EMPLOYEE_ID IN ('100', '104');
INSERT INTO HRS_EMPLOYEE_STORE (ORGANIZATION_ID, RTL_LOC_ID, EMPLOYEE_ID, EMPLOYEE_STORE_SEQ, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID) VALUES ($(OrgID), $(StoreID), '100', 0, SYSDATE, 'BASEDATA', SYSDATE, 'BASEDATA');
INSERT INTO HRS_EMPLOYEE_STORE (ORGANIZATION_ID, RTL_LOC_ID, EMPLOYEE_ID, EMPLOYEE_STORE_SEQ, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID) VALUES ($(OrgID), $(StoreID), '104', 0, SYSDATE, 'BASEDATA', SYSDATE, 'BASEDATA');

--crm_party
DELETE FROM CRM_PARTY WHERE ORGANIZATION_ID = $(OrgID) AND PARTY_ID IN ('100', '104');
INSERT INTO CRM_PARTY (ORGANIZATION_ID, PARTY_ID, FIRST_NAME, LAST_NAME, PARTY_TYPCODE, PREFERRED_LOCALE, ORGANIZATION_TYPCODE, ORGANIZATION_NAME, SOCIAL_SECURITY_NBR, EMPLOYEE_ID, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID) VALUES ($(OrgID), 100, 'John', 'Smith', 'EMPLOYEE', 'en_US', 'COMPANY', 'Oracle', '1231243203', '100', SYSDATE, 'BASEDATA', SYSDATE, 'BASEDATA');
INSERT INTO CRM_PARTY (ORGANIZATION_ID, PARTY_ID, FIRST_NAME, LAST_NAME, PARTY_TYPCODE, PREFERRED_LOCALE, ORGANIZATION_TYPCODE, ORGANIZATION_NAME, SOCIAL_SECURITY_NBR, EMPLOYEE_ID, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID) VALUES ($(OrgID), 104, 'Jeff', 'Black', 'EMPLOYEE', 'en_US', 'COMPANY', 'Oracle', '1231243203', '104', SYSDATE, 'BASEDATA', SYSDATE, 'BASEDATA');

-- IMPORT DEFAULT SYSTEM TEST USER
DELETE FROM CRM_PARTY WHERE ORGANIZATION_ID = $(OrgID) AND PARTY_ID = 0;
INSERT INTO CRM_PARTY (ORGANIZATION_ID, PARTY_ID, LAST_NAME, PARTY_TYPCODE, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID) VALUES ($(OrgID), 0, 'DEFAULT SYSTEM USER', 'SYSTEM', SYSDATE, 'BASEDATA', SYSDATE, 'BASEDATA');

DELETE FROM CRM_PARTY_LOCALE_INFORMATION WHERE ORGANIZATION_ID = $(OrgID) AND PARTY_ID = 0 AND PARTY_LOCALE_SEQ <= 1;
INSERT INTO CRM_PARTY_LOCALE_INFORMATION (ORGANIZATION_ID, PARTY_ID, PARTY_LOCALE_SEQ, PRIMARY_FLAG, ADDRESS1, CITY, STATE, POSTAL_CODE, COUNTRY, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID) VALUES ($(OrgID), 0, 1, 1, '30500 Bruce Industrial Pkwy', 'Solon', 'OH', '44139', 'US', SYSDATE, 'BASEDATA', SYSDATE, 'BASEDATA');

DELETE FROM CRM_PARTY_TELEPHONE WHERE ORGANIZATION_ID = $(OrgID) AND PARTY_ID = 0 AND TELEPHONE_TYPE = 'Home';
INSERT INTO CRM_PARTY_TELEPHONE (ORGANIZATION_ID, PARTY_ID, TELEPHONE_TYPE, TELEPHONE_NUMBER, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID) VALUES ($(OrgID), 0, 'Home', '4404984419', SYSDATE, 'BASEDATA', SYSDATE, 'BASEDATA');

DELETE FROM HRS_EMPLOYEE WHERE ORGANIZATION_ID = $(OrgID) AND EMPLOYEE_ID = '0';
INSERT INTO HRS_EMPLOYEE (ORGANIZATION_ID, EMPLOYEE_ID, LOGIN_ID, PARTY_ID, JOB_TITLE, EMPLOYEE_ROLE_CODE, GROUP_MEMBERSHIP, PRIMARY_GROUP, EMPLOYEE_TYPCODE, TRAINING_STATUS_ENUM,  EMPLOYEE_STATCODE, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID) VALUES ($(OrgID), '0', '0', 0, 'DEFAULT SYSTEM USER', 'EVERYONE', 'AQ==', 'EVERYONE', 'EVERYONE', 'EXEMPT', 'A', SYSDATE, 'BASEDATA', SYSDATE, 'BASEDATA');

-- START BZ26502
-- crm_party_locale_information 
DELETE FROM CRM_PARTY_LOCALE_INFORMATION WHERE ORGANIZATION_ID = $(OrgID) AND PARTY_ID IN ('100', '104');
INSERT INTO CRM_PARTY_LOCALE_INFORMATION (ORGANIZATION_ID, PARTY_ID, PARTY_LOCALE_SEQ, PRIMARY_FLAG, ADDRESS1, CITY, STATE, POSTAL_CODE, COUNTRY, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID) VALUES ($(OrgID), 100, 1, 1, '30500 Bruce Industrial Pkwy', 'Solon', 'OH', '44139', 'US', SYSDATE, 'BASEDATA', SYSDATE, 'BASEDATA');
INSERT INTO CRM_PARTY_LOCALE_INFORMATION (ORGANIZATION_ID, PARTY_ID, PARTY_LOCALE_SEQ, PRIMARY_FLAG, ADDRESS1, CITY, STATE, POSTAL_CODE, COUNTRY, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID) VALUES ($(OrgID), 104, 1, 1, '30500 Bruce Industrial Pkwy', 'Solon', 'OH', '44139', 'US', SYSDATE, 'BASEDATA', SYSDATE, 'BASEDATA');
-- END BZ26502
-- END IMPORT DATA OF 10 TEST USERS

COMMIT;
